# Generated by Django 6.0.1 on 2026-02-11 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={
                "ordering": ["-published_date", "-created_at"],
                "verbose_name": "Blog Post",
                "verbose_name_plural": "Blog Posts",
            },
        ),
        migrations.AlterField(
            model_name="blog",
            name="author",
            field=models.ForeignKey(
                blank=True,
                help_text="Tác giả của blog post",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="blogs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TECH", "Technology"),
                    ("LIFE", "Lifestyle"),
                    ("TRAVEL", "Travel"),
                    ("FOOD", "Food"),
                    ("SPORT", "Sports"),
                    ("OTHER", "Other"),
                ],
                help_text="Danh mục blog",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="content",
            field=models.TextField(help_text="Nội dung blog (hỗ trợ HTML)"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="featured_image",
            field=models.ImageField(
                blank=True,
                help_text="Ảnh đại diện cho blog",
                null=True,
                upload_to="blog_img/%Y/%m/",
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="is_draft",
            field=models.BooleanField(
                default=True, help_text="True nếu blog chưa publish"
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="published_date",
            field=models.DateTimeField(
                blank=True, help_text="Ngày publish blog (null nếu draft)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="slug",
            field=models.SlugField(
                blank=True,
                default=1,
                help_text="URL-friendly slug (tự động tạo từ title)",
                max_length=255,
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="blog",
            name="title",
            field=models.CharField(help_text="Tiêu đề blog post", max_length=255),
        ),
        migrations.AddIndex(
            model_name="blog",
            index=models.Index(fields=["slug"], name="blog_slug_idx"),
        ),
        migrations.AddIndex(
            model_name="blog",
            index=models.Index(fields=["category"], name="blog_category_idx"),
        ),
        migrations.AddIndex(
            model_name="blog",
            index=models.Index(
                fields=["is_draft", "published_date"], name="blog_published_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="blog",
            index=models.Index(
                fields=["author", "is_draft"], name="blog_author_draft_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="blog",
            index=models.Index(
                fields=["-published_date"], name="blog_pub_date_desc_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="blog",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_draft", True),
                    models.Q(("is_draft", False), ("published_date__isnull", False)),
                    _connector="OR",
                ),
                name="published_must_have_date",
            ),
        ),
    ]
