# Generated by Django 6.0.1 on 2026-02-12 07:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_alter_blog_options_alter_blog_author_and_more"),
        ("comments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Commment",
            new_name="Comment",
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Blog Comment",
                "verbose_name_plural": "Blog Comments",
            },
        ),
        migrations.AlterModelTable(
            name="comment",
            table="blog_comments",
        ),
    ]
